spring.application.name=Nexus Retail
spring.profiles.active=dev
api.base.path=nexusretail/api/v1
server.port=8080
spring.main.allow-bean-definition-overriding=true

# JWT Configuration
jwt.secret=7faaa14039adca7b2b348b9241f90c734a8e3d930e32f2e1a41e5ddbc4e72a47
jwt.expiration=3600000

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
